### ISSUE TITLE
Bower install failing for 1.2.0

### ISSUE THREAD

**Issue by eric-2d** [olimsaidov/pixeden-stroke-7-icon#2]
Hello,

First of, great font thanks for putting it together.

I can see that a pull request has been merged to fix the issue in the bower.json (the comma after "main" : "").
However the fix is in the master branch and is not in the tag "1.2.0". 
Therefore the fix is not available to bower:

bower pixeden-stroke-7-icon#1.2.0    download https://github.com/olimsaidov/pixeden-stroke-7-icon/archive/v1.2.0.tar.gz
This tarball doesn't have the fix

I tried to specify the previous version where the build was working: "1.1.0" but there is no tag for this version so bower can't find it! Would be great if you could keep the previous working version.

The workaround for now: specify 'master' as the version.
 "pixeden-stroke-7-icon": "master"
Bower will then fetch pixeden from the master branch. (not recommended)

**Comment by gelevanog** [comment]
+
